/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ProjectsImport } from './routes/projects'
import { Route as LoginImport } from './routes/login'
import { Route as EnvironmentsImport } from './routes/environments'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectProjectIdImport } from './routes/project.$projectId'
import { Route as ProjectProjectIdDeploymentsDeploymentIdImport } from './routes/project.$projectId.deployments.$deploymentId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRoute = ProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const EnvironmentsRoute = EnvironmentsImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectProjectIdRoute = ProjectProjectIdImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRoute,
} as any)

const ProjectProjectIdDeploymentsDeploymentIdRoute =
  ProjectProjectIdDeploymentsDeploymentIdImport.update({
    id: '/deployments/$deploymentId',
    path: '/deployments/$deploymentId',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdImport
      parentRoute: typeof rootRoute
    }
    '/project/$projectId/deployments/$deploymentId': {
      id: '/project/$projectId/deployments/$deploymentId'
      path: '/deployments/$deploymentId'
      fullPath: '/project/$projectId/deployments/$deploymentId'
      preLoaderRoute: typeof ProjectProjectIdDeploymentsDeploymentIdImport
      parentRoute: typeof ProjectProjectIdImport
    }
  }
}

// Create and export the route tree

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdDeploymentsDeploymentIdRoute: typeof ProjectProjectIdDeploymentsDeploymentIdRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdDeploymentsDeploymentIdRoute:
    ProjectProjectIdDeploymentsDeploymentIdRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/environments': typeof EnvironmentsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/signup': typeof SignupRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/deployments/$deploymentId': typeof ProjectProjectIdDeploymentsDeploymentIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/environments': typeof EnvironmentsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/signup': typeof SignupRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/deployments/$deploymentId': typeof ProjectProjectIdDeploymentsDeploymentIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/environments': typeof EnvironmentsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/signup': typeof SignupRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/deployments/$deploymentId': typeof ProjectProjectIdDeploymentsDeploymentIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/environments'
    | '/login'
    | '/projects'
    | '/signup'
    | '/project/$projectId'
    | '/project/$projectId/deployments/$deploymentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/environments'
    | '/login'
    | '/projects'
    | '/signup'
    | '/project/$projectId'
    | '/project/$projectId/deployments/$deploymentId'
  id:
    | '__root__'
    | '/'
    | '/environments'
    | '/login'
    | '/projects'
    | '/signup'
    | '/project/$projectId'
    | '/project/$projectId/deployments/$deploymentId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  SignupRoute: typeof SignupRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  SignupRoute: SignupRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/environments",
        "/login",
        "/projects",
        "/signup",
        "/project/$projectId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/environments": {
      "filePath": "environments.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/projects": {
      "filePath": "projects.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/project/$projectId": {
      "filePath": "project.$projectId.tsx",
      "children": [
        "/project/$projectId/deployments/$deploymentId"
      ]
    },
    "/project/$projectId/deployments/$deploymentId": {
      "filePath": "project.$projectId.deployments.$deploymentId.tsx",
      "parent": "/project/$projectId"
    }
  }
}
ROUTE_MANIFEST_END */
